quarkus.http.port=8083

quarkus.datasource.db-kind=mysql
quarkus.datasource.username=user
quarkus.datasource.password=pass
%prod.quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/inventory

quarkus.flyway.migrate-at-start=true